### ISSUE TITLE
Shows as evince in AppCenter instead of Document Viewer

### ISSUE THREAD

**Issue by ekecso** [elementary/evince#15]
## What Happened

In AppCenter, I saw an update for evince and didn't know what it was.

## Expected Behavior

Evince should show as Document Viewer and with Document Viewer icon.

## Steps to Reproduce

1. Open AppCenter
2. If there is an update for evince, it shows that instead of document viewer

**Comment by cassidyjames** [comment]
I guess we could patch AppData… :thinking:

**Comment by ryonakano** [comment]
This seems like fixed in elementary OS 7:

![VirtualBox_eOS 7 en_US_25_03_2023_17_31_58](https://user-images.githubusercontent.com/26003928/227706532-f0a2540b-c0ee-4b7c-be05-4d59a0f52c8c.png)

**Comment by danirabbit** [comment]
I can also confirm that this was fixed
