### ISSUE TITLE
Automatically toggle "night mode" when using system dark style

### ISSUE THREAD

**Issue by danrabbit** [elementary/evince#22]
## Problem

There's a separate toggle in Evince's settings menu for "night mode" that doesn't get automatically changed when using the system dark style

## Proposal

We should probably change this automatically for full dark style support? But I imagine we'd want to still be able to toggle it off in case the PDF renders funny?

**Comment by andrewdbate** [comment]
If I've understood you correctly you are referring to this option:
![Screenshot from 2022-03-20 21 38 48](https://user-images.githubusercontent.com/2998569/159187075-6f5beda6-a828-4b02-be91-613d20983035.png)

I _really_ don't think you would want to toggle that option automatically in dark mode. I would never expect my system theme settings to change that.

For example, here is a PDF copy of the book _Linux Security Cookbook_ both with and without the Night Mode setting:

Before:
![Screenshot from 2022-03-20 21 44 40](https://user-images.githubusercontent.com/2998569/159187236-be4fcb9c-1032-4c35-a972-747ffb403525.png)
After:
![Screenshot from 2022-03-20 21 44 45](https://user-images.githubusercontent.com/2998569/159187251-cd7f6047-3ba9-4d0b-8a05-f69d7ed9d794.png)

I **really** would not expect changing my system theme to change how my books look!

Now as a user to be be able to read books with illustrations/figures normally I need to know that this Night Mode option even exists, and then go turn it off.

I notice you say that "I imagine we'd want to still be able to toggle it off". I wouldn't even consider removing the Night Mode option. That would be a disaster from a usability point-of-view.

**Comment by danrabbit** [comment]
Ah, I didn't realize this feature is a bit more invasive than I thought it was. Closing

**Comment by Francewhoa** [comment]
For those interested in an automated Night mode for Evince (Document Viewer). The latest version of Evince has better support for Night Mode/Dark Mode at https://flathub.org/apps/org.gnome.Evince

Steps, screenshots, and details are in my comment at https://www.reddit.com/r/linux4noobs/comments/12jptzb/comment/kvxim2s/

**Comment by danirabbit** [comment]
@Francewhoa we're already shipping the latest Evince in elementary OS, so this just works :)
