### ISSUE TITLE
CUPS sandbox hole shouldn't be necessary

### ISSUE THREAD

**Issue by danirabbit** [elementary/evince#32]
### What Happened?

Follow up for #19 

We should have a printing portal here and not need CUPS sandbox hole

### Steps to Reproduce

See issues #10 and #18 for what happens when we don't have this hole in the sandbox

### Expected Behavior

We should be able to retain functionality using the printing portal

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Maybe we can now close this issue since #46 gets merged?
