### ISSUE TITLE
Unable to open Postscript files

### ISSUE THREAD

**Issue by andrewdbate** [elementary/evince#40]
### What Happened?

Evince supports Postscript files well. For example, you can open a Postscript file in Evince on Ubuntu.

However, the flatpak version of Evice provided with Elementary does not support Postscript files.

I believe that this is because the `--enable-ps` option is required when building Evince. (See https://github.com/clearlinux/distribution/issues/1793 for a similar resolved ssue on Clear Linux.)

### Steps to Reproduce

1. Open any Postscript file with Evince
2. You get the error "Unable to open document".

### Expected Behavior

You should be able to open Postscript files with Evince on Elementary because you can on Ubuntu and anywhere else Evince is packaged and available.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

N/A

**Comment by tintou** [comment]
See also https://github.com/flathub/org.gnome.Evince/issues/71 for the reasoning

**Comment by danirabbit** [comment]
Closing as "Not Planned" since this is an upstream issue

**Comment by andrewdbate** [comment]
The reasoning given in https://github.com/flathub/org.gnome.Evince/issues/71 was that it would pull in too many dependencies.

Does elementary have an opinion on this? Could we not pull in such dependencies and built it ourselves? Or is it the case that the team does not have the resources to do so?

It is very annoying from a usability point-of-view that the elementary version of Evince is less capable than the Ubuntu one. Thanks!
