### ISSUE TITLE
Feature request: Enable "Ctrl+q" for exit

### ISSUE THREAD

**Issue by decembre-dhiver** [elementary/evince#52]
### Problem

I often work with pdf documents and etc. So when I'm done, I love spam ctrl+q to close all apps, but evince doesn't support this feature

### Proposal

Make the app adhere "ctrl+q" shortcut as most of native apps

**Comment by danirabbit** [comment]
This is probably more invasive than a change we want to carry as a downstream patch. Please report this upstream: https://gitlab.gnome.org/GNOME/evince/-/issues

**Comment by decembre-dhiver** [comment]
All right. Thank you
