### ISSUE TITLE
Does not respect dark mode

### ISSUE THREAD

**Issue by kdwk** [elementary/evince#9]
## What Happened

Even when system style is set to 'dark' in Settings-> Desktop-> Appearance, Document Viewer still stays in light mode with light gray UI elements.

## Expected Behavior

Document Viewer should have darker UI elements when in dark mode.

## Steps to Reproduce

1. Set dark mode
2. Open a document with Document Viewer

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/125953446-82f1059b-1a29-42f0-8f4b-ed2a8536ecd8.png)

**Comment by danrabbit** [comment]
Thanks for your report! I'm not sure we've done any kind of testing to make sure that Evince works with dark mode. We'll need to prepare a patch like we did with GNOME Web to listen to the dark style setting as well as see if there are any issues introduced that would make Evince unusable with a dark style

**Comment by ldesousa** [comment]
I am having this issue on Ubuntu 22.04 with Regolith 4.3. Is there any setting in Evince itself that could help it acknowledging the DE theme?

**Comment by danirabbit** [comment]
@ldesousa this tracker is specifically for the Flatpak version of evince that's packaged for elementary OS. You'll need to pursue issues experienced with Ubuntu in their issue tracker. As of version 42 Evince supports the freedesktop dark style so this is likely in issue in your distribution or desktop environment
